
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mert Bilgic
 */
public class KarBilgisi extends javax.swing.JFrame {
    DefaultTableModel model,model2;
    İslemler islem = new İslemler();
    /**
     * Creates new form KarBilgisi
     */
    public KarBilgisi() {
        initComponents();
        model = (DefaultTableModel) urun_kar.getModel();
        model2= (DefaultTableModel) musteri_kar.getModel();
        tablo_doldur();
        tablo_doldur2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        urun_kar = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        musteri_kar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kapat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        urun_kar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Urun_ID", "Urun_Adı", "Bileşenler", "Kar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(urun_kar);
        if (urun_kar.getColumnModel().getColumnCount() > 0) {
            urun_kar.getColumnModel().getColumn(0).setResizable(false);
            urun_kar.getColumnModel().getColumn(1).setResizable(false);
            urun_kar.getColumnModel().getColumn(2).setResizable(false);
            urun_kar.getColumnModel().getColumn(3).setResizable(false);
        }

        musteri_kar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Musteri_ID", "Urun_ID", "Kar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(musteri_kar);
        if (musteri_kar.getColumnModel().getColumnCount() > 0) {
            musteri_kar.getColumnModel().getColumn(0).setResizable(false);
            musteri_kar.getColumnModel().getColumn(1).setResizable(false);
            musteri_kar.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setText("Ürün Bazında Kar:");

        jLabel2.setText("Müşteri Bazında Kar:");

        kapat.setText("Sekmeyi Kapat");
        kapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kapatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kapat)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kapat)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kapatActionPerformed
        setVisible(false);
    }//GEN-LAST:event_kapatActionPerformed

    /**
     * @param args the command line arguments
     */
    public void tablo_doldur(){
        model.setRowCount(0);
    
       ArrayList<p1_tablo> cikti = new ArrayList<p1_tablo>();
       
       cikti=islem.urun_kar();
         
        if(cikti!=null){
      
            for(p1_tablo veri : cikti){
                
                Object[] eklenecek ={veri.getUrun_id(),veri.getUrun_adi(),veri.getBilesen(),veri.getKar()};
                model.addRow(eklenecek);
            }       
        }
    }
    public void tablo_doldur2(){
        model2.setRowCount(0);
    
       ArrayList<p1_tablo> cikti = new ArrayList<p1_tablo>();
       
       cikti=islem.musteri_kar();
         
        if(cikti!=null){
      
            for(p1_tablo veri : cikti){
                
                Object[] eklenecek ={veri.getMusteri_id(),veri.getUrun_id(),veri.getKar()};
                model2.addRow(eklenecek);
            }       
        }
    }
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KarBilgisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KarBilgisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KarBilgisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KarBilgisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KarBilgisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kapat;
    private javax.swing.JTable musteri_kar;
    private javax.swing.JTable urun_kar;
    // End of variables declaration//GEN-END:variables
}
