
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mert Bilgic
 */
public class MusteriAlım extends javax.swing.JFrame {
    DefaultTableModel model,model2,model3,model4,model5;
    İslemler islem = new İslemler();
    final int yetersiz_ürün_kodu=9999;
    /**
     * Creates new form UrunAl
     */
 
       
       
    public MusteriAlım() {
        initComponents();
        model = (DefaultTableModel) p1_tablo.getModel();
        model2 = (DefaultTableModel) u_bilgisi.getModel();
        model3 = (DefaultTableModel) kimysal.getModel();
        model4 = (DefaultTableModel) m_kimyasal.getModel();
        model5 = (DefaultTableModel) Musteri.getModel();
        tablo_doldur();
        tablo_doldur2();
        tablo_doldur3();
        tablo_doldur4();
        tablo_doldur5();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void tablo_doldur(){
        model.setRowCount(0);
        
        ArrayList<p1_tablo> cikti = new ArrayList<p1_tablo>();
        
                cikti = islem.p1_tablo_getir();
        
        if(cikti!=null){
            
            
            for(p1_tablo veri : cikti){
                
                Object[] eklenecek ={veri.getFirma_id(),veri.getFirma_adi(),veri.getM_id(),veri.getHammade(),veri.getMiktar(),veri.getMaliyet(),veri.getKargo(),veri.getUlke(),veri.getRaf_omru(),veri.getTarih()};
                model.addRow(eklenecek);
            }
        }
        
    }
    public void tablo_doldur2(){
       model2.setRowCount(0);
        
        ArrayList<p1_tablo> cikti = new ArrayList<p1_tablo>();
        
                cikti = islem.u_bilgisi_tablo_getir();
                
        if(cikti!=null){
            
            
            for(p1_tablo veri : cikti){
                //System.out.println(veri.getFirma_id()+"  "+veri.getM_id()+"  "+veri.getHammade()+" "+ veri.getMiktar()+"  "+veri.getMaliyet());
                Object[] eklenecek ={veri.getFirma_id(),veri.getM_id(),veri.getHammade(),veri.getMiktar(),veri.getMaliyet(),veri.getTarih()};
                model2.addRow(eklenecek);
            }
        }  
   }
    public void tablo_doldur3(){
       model3.setRowCount(0);
        
        ArrayList<p1_tablo> cikti = new ArrayList<p1_tablo>();
        
                cikti = islem.urun_bilgisi_getir();
                
        if(cikti!=null){
            
            
            for(p1_tablo veri : cikti){
                //System.out.println(veri.getFirma_id()+"  "+veri.getM_id()+"  "+veri.getHammade()+" "+ veri.getMiktar()+"  "+veri.getMaliyet());
                Object[] eklenecek ={veri.getUrun_id(),veri.getUrun_adi(),veri.getBilesen(),veri.getMiktar(),veri.getRaf_omru()};
                model3.addRow(eklenecek);
            }
        }  
   }
    public void tablo_doldur4(){
       model4.setRowCount(0);
        
        ArrayList<p1_tablo> cikti = new ArrayList<p1_tablo>();
        
                cikti = islem.m_urun_bilgisi_getir();
                
        if(cikti!=null){
            
            for(p1_tablo veri : cikti){
                //System.out.println(veri.getFirma_id()+"  "+veri.getM_id()+"  "+veri.getHammade()+" "+ veri.getMiktar()+"  "+veri.getMaliyet());
                Object[] eklenecek ={veri.getMusteri_id(),veri.getUrun_id(),veri.getUrun_adi(),veri.getMaliyet(),veri.getMiktar()};
                model4.addRow(eklenecek);
            }
        }  
   }
    public void tablo_doldur5(){
       model5.setRowCount(0);
        
        ArrayList<p1_tablo> cikti = new ArrayList<p1_tablo>();
        
                cikti = islem.musteri_bilgisi_getir();
                
        if(cikti!=null){
            
            for(p1_tablo veri : cikti){
                //System.out.println(veri.getFirma_id()+"  "+veri.getM_id()+"  "+veri.getHammade()+" "+ veri.getMiktar()+"  "+veri.getMaliyet());
                Object[] eklenecek ={veri.getMusteri_id(),veri.getMusteri_adi(),veri.getAdres(),veri.getSehir(),veri.getUlke(),veri.getKargo()};
                model5.addRow(eklenecek);
            }
        }  
   }
    boolean sayi_mi(char girilen){
        
        int giris =girilen;
        boolean sonuc=false;
        if(giris>64 && giris<91 || giris>96 && giris<123){
             sonuc = true;
        }
        return sonuc;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kapat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        kimysal = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        m_kimyasal = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        İstenilen_Urun = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        miktar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Musteri_ID = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        uyari_alani = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        p1_tablo = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        u_bilgisi = new javax.swing.JTable();
        urun_al = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Musteri = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        karr = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kapat.setText("Sekme Kapat");
        kapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kapatActionPerformed(evt);
            }
        });

        kimysal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Urun_ID", "Urun Adı", "Bilesenleri", "Stok", "Raf_omru"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(kimysal);
        if (kimysal.getColumnModel().getColumnCount() > 0) {
            kimysal.getColumnModel().getColumn(0).setResizable(false);
            kimysal.getColumnModel().getColumn(1).setResizable(false);
            kimysal.getColumnModel().getColumn(2).setResizable(false);
            kimysal.getColumnModel().getColumn(3).setResizable(false);
            kimysal.getColumnModel().getColumn(4).setResizable(false);
        }

        m_kimyasal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Musteri_ID", "Urun_ID", "Urun_Adı", "Alıs_Fiyatı", "Stok Durumu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(m_kimyasal);
        if (m_kimyasal.getColumnModel().getColumnCount() > 0) {
            m_kimyasal.getColumnModel().getColumn(0).setResizable(false);
            m_kimyasal.getColumnModel().getColumn(1).setResizable(false);
            m_kimyasal.getColumnModel().getColumn(2).setResizable(false);
            m_kimyasal.getColumnModel().getColumn(3).setResizable(false);
            m_kimyasal.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setText("Üretici Kimyasal Bİlgisi:");

        jLabel2.setText("Müşteri Kimyasal  Bilgisi:");

        jLabel3.setText("İstenilen Ürün(H2/O):");

        jLabel4.setText("Miktar:");

        jLabel5.setText("Alıcı(Müşteri_ID):");

        uyari_alani.setColumns(20);
        uyari_alani.setRows(5);
        jScrollPane3.setViewportView(uyari_alani);

        jLabel6.setText("Uyari Yazısı:");

        p1_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Firma_id", "Firma_Adı", "M_id", "Hammade", "Miktar", "Satis", "Uzaklık", "Ülke", "Raf_omru", "U_Tarihi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        p1_tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1_tabloMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(p1_tablo);

        u_bilgisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "firma_id", "m_id", "hammade", "stok_durumu", "alıs_fiyatı", "SKT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(u_bilgisi);

        urun_al.setText("Urun al");
        urun_al.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urun_alActionPerformed(evt);
            }
        });

        jLabel7.setText("Tedarikçi Hammadde Bilgisi:");

        jLabel8.setText("Üretici Hammade Bilgisi:");

        Musteri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Musteri_ID", "Musteri_Adi", "Adres", "Sehir", "Ulke"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(Musteri);
        if (Musteri.getColumnModel().getColumnCount() > 0) {
            Musteri.getColumnModel().getColumn(0).setResizable(false);
            Musteri.getColumnModel().getColumn(1).setResizable(false);
            Musteri.getColumnModel().getColumn(2).setResizable(false);
            Musteri.getColumnModel().getColumn(3).setResizable(false);
            Musteri.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel9.setText("Müşteri Bilgisi:");

        jLabel10.setText("Kar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kapat))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(365, 365, 365)
                                        .addComponent(jLabel2))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(327, 327, 327)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(karr))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(miktar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(İstenilen_Urun, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(Musteri_ID)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(urun_al, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kapat)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Musteri_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(İstenilen_Urun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(miktar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(karr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(urun_al, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kapatActionPerformed
       
        setVisible(false);
    }//GEN-LAST:event_kapatActionPerformed

    private void p1_tabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1_tabloMouseClicked

       /* selectedrow = p1_tablo.getSelectedRow();

        miktar_alani.setText(model.getValueAt(selectedrow,4).toString());
        satis_alani.setText(model.getValueAt(selectedrow,5).toString());
        tarih_alani.setText(model.getValueAt(selectedrow,9).toString());*/

    }//GEN-LAST:event_p1_tabloMouseClicked

    private void urun_alActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urun_alActionPerformed
        islem.genel_toplam=0;
        islem.toplam_alım=0;
        String mesaj="";
        int durum=0;
        int musteri_ıd= Integer.valueOf(Musteri_ID.getText());
        int t_miktar= Integer.valueOf(miktar.getText());
        int kar=20;
        if(karr.getText().length()>0)
        kar = Integer.valueOf(karr.getText());
        
        String text=İstenilen_Urun.getText();
        String bilesen="";
        String urun_adi="";
        String sayi="0";
        String[] bil = new String[10];
        int[] adet = new int[10];
        int k=0,t=0;
        for(int i=0;i<text.length();i++){
            
            if(k==0&&text.charAt(i)!='/'){
                bilesen+=text.charAt(i);
                bil[t]="";
                bil[t]+=text.charAt(i);
            }
            else if(text.charAt(i)!='/'){
                
               boolean sonuc =sayi_mi(text.charAt(i));
                if(sonuc)
                 bil[t]+=text.charAt(i);   
                else
                sayi+=text.charAt(i); 
            }
            if(text.charAt(i)!='/'){
                
                urun_adi+=text.charAt(i);
                k++;
            }
            else{
                
                k=0;
                bilesen+="-";
                adet[t]=Integer.valueOf(sayi);
                t++;
                sayi="0";
            }
        }
        adet[t]=Integer.valueOf(sayi);
        t++;
        //İstenilen ürün stokta var mı kontrol yapıyor
        int hata_kodu=islem.kimysal_stok_var_mi(urun_adi, t_miktar);
        
        System.out.println("kimysal_stok_var_mi:      "+hata_kodu);
        
        if(t_miktar>hata_kodu&&hata_kodu!=yetersiz_ürün_kodu){
           t_miktar-=hata_kodu;
           //Firmanın içindeki hammade kontrolünü yapıyor
           hata_kodu= islem.stokta_var_mı(bil, adet, t, t_miktar);
           System.out.println("stokta_var_mı:      "+hata_kodu);
           }
          
            if(hata_kodu==yetersiz_ürün_kodu){
              hata_kodu=islem.musteri_eksik_hammade(bil, adet, t, t_miktar);
                System.out.println("musteri_eksik_hammade----------->:"+hata_kodu);
                durum++;
                
              if(hata_kodu==yetersiz_ürün_kodu){
                  uyari_alani.setText(mesaj+İslemler.uyari3+"Tedarikçidede Stok YOK");
                    tablo_doldur();
                    tablo_doldur2();
                    tablo_doldur3();
                    tablo_doldur4();
                    tablo_doldur5();
                  return;
              }else{
                  islem.kimyasal_var_mı(urun_adi,bilesen,bil,adet,t,t_miktar,kar);
              }
              
            }
            if(hata_kodu!=yetersiz_ürün_kodu){
            //Tedarikçiden firmaya ürün alımı yapılıyor
            islem.firma_urun_al(bil, adet, t, t_miktar);
            //Hiç üretilmemiş mi yoksa daha önce üretimi yapılmış bir ürün mü diye kontrol yapılıyor
            
            islem.musteri_urun_al(urun_adi, t_miktar,musteri_ıd,durum);
            }else{
                return;
                //mesaj="İstenilen ürün için gerekli olan\n hammadde tedarikçide de bulunnmamaktadır";
            }
        
        
            
        
            uyari_alani.setText(mesaj+İslemler.uyari3);
        
        
        
        
        
        
       
        
        
        tablo_doldur();
        tablo_doldur2();
        tablo_doldur3();
        tablo_doldur4();
        tablo_doldur5();
    }//GEN-LAST:event_urun_alActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriAlım.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriAlım.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriAlım.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriAlım.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriAlım().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Musteri;
    private javax.swing.JTextField Musteri_ID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton kapat;
    private javax.swing.JTextField karr;
    private javax.swing.JTable kimysal;
    private javax.swing.JTable m_kimyasal;
    private javax.swing.JTextField miktar;
    private javax.swing.JTable p1_tablo;
    private javax.swing.JTable u_bilgisi;
    private javax.swing.JButton urun_al;
    private javax.swing.JTextArea uyari_alani;
    private javax.swing.JTextField İstenilen_Urun;
    // End of variables declaration//GEN-END:variables
}
