
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mert Bilgic
 */
public class TedarikciEkle extends javax.swing.JFrame {
    DefaultTableModel model,model2;
    İslemler islem = new İslemler();
    SimpleDateFormat bicim=new SimpleDateFormat("ddMMyyyy");
    Date tarih=new Date();
    String tarih2=bicim.format(tarih);
    /**
     * Creates new form TedarikciEkle
     */
    public TedarikciEkle() {
        initComponents();
        model = (DefaultTableModel) p1_tablo.getModel();
        model2 = (DefaultTableModel) firma_bilgisi.getModel();
        tablo_doldur();
        tablo_doldur2();
    }
    public void tablo_doldur(){
        model.setRowCount(0);
        
        ArrayList<p1_tablo> cikti = new ArrayList<p1_tablo>();
        
                cikti = islem.p1_tablo_getir();
        
        if(cikti!=null){
            
            
            for(p1_tablo veri : cikti){
                
                Object[] eklenecek ={veri.getFirma_id(),veri.getFirma_adi(),veri.getM_id(),veri.getHammade(),veri.getMiktar(),veri.getMaliyet(),veri.getKargo(),veri.getUlke(),veri.getRaf_omru(),veri.getTarih()};
                model.addRow(eklenecek);
            }
        }
        
    }
       
    public void tablo_doldur2(){
       model2.setRowCount(0);
        
        ArrayList<p1_tablo> cikti = new ArrayList<p1_tablo>();
        
                cikti = islem.firma_bilgisi_tablo();
                
        if(cikti!=null){
            
            
            for(p1_tablo veri : cikti){
                
                Object[] eklenecek ={veri.getFirma_id(),veri.getFirma_adi(),veri.getSehir(),veri.getUlke(),veri.getKargo()};
                model2.addRow(eklenecek);
            }
        } 
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tedarikçi_ekle = new javax.swing.JButton();
        fimra_adi = new javax.swing.JTextField();
        ulke = new javax.swing.JTextField();
        sehir = new javax.swing.JTextField();
        hammade = new javax.swing.JTextField();
        miktar = new javax.swing.JTextField();
        satis = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        uzaklik = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        firma_bilgisi = new javax.swing.JTable();
        kapat = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        p1_tablo = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        firma_id = new javax.swing.JTextField();
        urun_ekle = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Uyari = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Firma Adı:");

        jLabel2.setText("Ülke:");

        jLabel3.setText("Şehir:");

        jLabel4.setText("Hammadde:");

        jLabel5.setText("Miktar:");

        jLabel6.setText("Satış Fiyatı:");

        tedarikçi_ekle.setText("Tedarikçi Ekle");
        tedarikçi_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tedarikçi_ekleActionPerformed(evt);
            }
        });

        hammade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hammadeActionPerformed(evt);
            }
        });

        jLabel7.setText("Uzaklık:");

        firma_bilgisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Firma_ID", "Firma_Adı", "Şehir", "Ulke", "Uzaklık"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(firma_bilgisi);
        if (firma_bilgisi.getColumnModel().getColumnCount() > 0) {
            firma_bilgisi.getColumnModel().getColumn(0).setResizable(false);
            firma_bilgisi.getColumnModel().getColumn(1).setResizable(false);
            firma_bilgisi.getColumnModel().getColumn(2).setResizable(false);
            firma_bilgisi.getColumnModel().getColumn(3).setResizable(false);
            firma_bilgisi.getColumnModel().getColumn(4).setResizable(false);
        }

        kapat.setText("Sekme Kapat");
        kapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kapatActionPerformed(evt);
            }
        });

        jLabel8.setText("Firma Bİlgisi");

        jLabel9.setText("Ürün Bİlgisi");

        p1_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Firma_id", "Firma_Adı", "M_id", "Hammade", "Miktar", "Satis", "Uzaklık", "Ülke", "Raf_omru", "U_Tarihi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        p1_tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1_tabloMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(p1_tablo);

        jLabel10.setText("Firma_ID:");

        urun_ekle.setText("Ürün Ekle");
        urun_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urun_ekleActionPerformed(evt);
            }
        });

        Uyari.setColumns(20);
        Uyari.setRows(5);
        jScrollPane2.setViewportView(Uyari);

        jLabel11.setText("Uyari Yazisi:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tedarikçi_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(329, 329, 329)
                                .addComponent(urun_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(158, 158, 158))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(fimra_adi, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ulke)))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sehir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(uzaklik, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firma_id, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(miktar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(satis, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hammade, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(fimra_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(sehir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ulke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(uzaklik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tedarikçi_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urun_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(firma_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(hammade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(miktar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(satis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(127, 127, 127))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hammadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hammadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hammadeActionPerformed

    private void tedarikçi_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tedarikçi_ekleActionPerformed
        
        String t_firma_adi=fimra_adi.getText();
        String t_sehir= sehir.getText();
        String t_ulke= ulke.getText();
        
        int t_uzaklik= Integer.valueOf(uzaklik.getText()); 
        
        islem.tedarikci_ekle(t_firma_adi,t_sehir,t_ulke,t_uzaklik);

        tablo_doldur();
        tablo_doldur2();    
        
    }//GEN-LAST:event_tedarikçi_ekleActionPerformed

    private void p1_tabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1_tabloMouseClicked

        //selectedrow = p1_tablo.getSelectedRow();

        //miktar_alani.setText(model.getValueAt(selectedrow,4).toString());
        ///satis_alani.setText(model.getValueAt(selectedrow,5).toString());
       // tarih_alani.setText(model.getValueAt(selectedrow,9).toString());

    }//GEN-LAST:event_p1_tabloMouseClicked

    private void kapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kapatActionPerformed
        setVisible(false);
    }//GEN-LAST:event_kapatActionPerformed

    private void urun_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urun_ekleActionPerformed
        String t_hammade=hammade.getText();
        
        int t_miktar=Integer.valueOf(miktar.getText());
        int t_satis =Integer.valueOf(satis.getText());
        int t_firma_id=Integer.valueOf(firma_id.getText());
        
        islem.t_anatablo_ekle(t_firma_id, t_miktar, t_satis, t_hammade, tarih2);
        
                Uyari.setText("");
       //System.out.println("\n"+İslemler.uyari);
        Uyari.setText(İslemler.uyari2);
        
        tablo_doldur();
        tablo_doldur2();
        
    }//GEN-LAST:event_urun_ekleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TedarikciEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TedarikciEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TedarikciEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TedarikciEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TedarikciEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Uyari;
    private javax.swing.JTextField fimra_adi;
    private javax.swing.JTable firma_bilgisi;
    private javax.swing.JTextField firma_id;
    private javax.swing.JTextField hammade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton kapat;
    private javax.swing.JTextField miktar;
    private javax.swing.JTable p1_tablo;
    private javax.swing.JTextField satis;
    private javax.swing.JTextField sehir;
    private javax.swing.JButton tedarikçi_ekle;
    private javax.swing.JTextField ulke;
    private javax.swing.JButton urun_ekle;
    private javax.swing.JTextField uzaklik;
    // End of variables declaration//GEN-END:variables
}
